-- P-1 Implement SQL queries to perform various DDL commands.

Table - 1
Create table CLIENT_MASTER(CLIENT_NO VARCHAR2(6),NAME VARCHAR2(20),ADDRESS1 VARCHAR2(30),ADDRESS2 VARCHAR2(30),CITY VARCHAR2(15),PINCODE VARCHAR2(8),STATE VARCHAR2(15),BALDUE NUMBER(10,2));

Table - 2
Create table PRODUCT_MASTER(PRODUCTNO VARCHAR2(6),DESCRIPTION VARCHAR2(15),PROFITPERCENT NUMBER(4,2),UNITMEASURE VARCHAR2(10),QTYONHAND NUMBER(8),REORDERLVL NUMBER(8),SELLPRICE NUMBER(8,2),COSTPRICE NUMBER(8,2));

Table - 3
Create table SALESMAN_MASTER(SALESMANNO VARCHAR2(6),SALESMANNAME VARCHAR2(20),ADDRESS1 VARCHAR2(30),ADDRESS2 VARCHAR2(30),CITY VARCHAR2(20),PINCODE NUMBER(8),STATE VARCHAR2(20),SALAMT NUMBER(8,2),TGTTOGET NUMBER(6,2),YTDSALES NUMBER(6,2),REMARKS VARCHAR2(60));

Table - 4
Create table CLNT_MASTER(CLIENTNO VARCHAR2(6) Primary Key,NAME VARCHAR2(20) NOT NULL,ADDRESS1 VARCHAR2(30),ADDRESS2 VARCHAR2(30),CITY VARCHAR2(15),PINCODE NUMBER(8),STATE VARCHAR2(10),BALDUE NUMBER(10,2),check(CLIENTNO Like('C%')));

Table - 5
Create table PRO_MASTER(PRODUCTNO VARCHAR2(6) Primary Key,Check(PRODUCTNO Like('P%')),DESCRIPTION VARCHAR2(15) NOT NULL,PROFITPERCENT NUMBER(4,2) NOT NULL,QTYONHAND NUMBER(8) NOT NULL,REORDERVL NUMBER(8) NOT NULL,
  SELLPRICE NUMBER(8,2) NOT NULL,Check(SELLPRICE ! = 0),COSTPRICE NUMBER(8,2) NOT NULL,Check (COSTPRICE ! = 0));

Table - 6
Create table SALES_MASTER(SALESMANNO VARCHAR2(6) Primary Key,Check(SALESMANNO Like('S%')),SALESMANNAME VARCHAR2(20) NOT NULL,ADDRESS1 VARCHAR2(30) NOT NULL,ADDRESS2 VARCHAR2(30),CITY VARCHAR2(20),PINCODE NUMBER(8),STATE VARCHAR2(20),SALAMT NUMBER(8,2) NOT NULL,
  Check(SALAMT Like('! = 0')),TGTTOGET NUMBER(6,2) NOT NULL,Check(TGTTOGET Like('! = 0')),YTDSALES NUMBER(6,2) NOT NULL,REMARKS VARCHAR2(60));

Table - 7
Create table SALES_ORDER(ORDERNO Varchar2(6) primary key Check(ORDERNO Like('O%')),CLIENTNO Varchar2(6) References CLNT_MASTER(CLIENTNO),ORDERDATE Date NOT NULL,DELYADDR Varchar2(25),SALESMANNO Varchar2(6) References SALES_MASTER(SALESMANNO),
  DELYTYPE Char(1) DEFAULT 'F' Check(DELYTYPE IN('P'/'F')),BILLYN Char(1),DELYDATE Date,ORDERSTATUS Varchar2(10) Check(ORDERSTATUS IN('In Process','Fulfilled','Back Order','Cancelled')));

Table - 8
Create table SALES_ORDER_DETAIL(ORDERNO Varchar2(6) References SALES_ORDER(ORDERNO),PRODUCTNO Varchar2(6) References PRO_MASTER(PRODUCTNO),QTYORDERED Number(6),QTYDISP Number(8),PRODUCTRATE Number(10,2));

Table - 9
Create table DEPT(DEPTNO Number(2) Primary key,DNAME Varchar2(14),LOC Varchar2(13));

Table - 10
Create table EMP(EMPNO Number(4) Primary key,ENAME Varchar2(10),JOB Varchar2(9),MGR Number(4),HIREDATE Date,SAL Number(7,2),COMM Number(7,2),DEPTNO Number(2) References DEPT(DEPTNO));


alter table CLIENT_MASTER add (state varchar2(15));

alter table PRODUCT_MASTER modify(SELLPRICE NUMBER(10,2));

alter table SALESMAN_MASTER drop(ADDRESS1);

rename CLNT_MASTER to CLIENT;

truncate table DEPT;

drop table DEPT;
