-- P-10 Implement SQL queries using GROUP functions.

1. SELECT * FROM CLIENT
WHERE BalDue > 10000;

2. SELECT * FROM PRODUCT_MASTER
WHERE SELLPRICE > 500 AND SELLPRICE <= 750;

3. SELECT PRODUCTNO, DESCRIPTION, SELLPRICE, SELLPRICE * 0.15 AS new_price
FROM PRODUCT_MASTER
WHERE SELLPRICE > 500;

4. SELECT COUNT(*) AS total_orders
FROM SALES_ORDER1;

5. SELECT AVG(SELLPRICE) AS average_price
FROM PRODUCT_MASTER;

6. SELECT MAX(SELLPRICE) AS max_price, MIN(SELLPRICE) AS min_price
FROM PRODUCT_MASTER;

7. SELECT COUNT(*) AS num_products_below_500
FROM PRODUCT_MASTER
WHERE SELLPRICE <= 500;

8. SELECT PRODUCTNO, DESCRIPTION, QTYONHAND, REORDERLVL, SELLPRICE
FROM PRODUCT_MASTER
WHERE QTYONHAND < REORDERLVL;

9. SELECT COUNT(*) AS total_clients
FROM CLIENT_MASTER;

10. select * from EMP where sal IN(select MIN(sal)from EMP);

11. SELECT DESCRIPTION
FROM PRODUCT_MASTER
WHERE SELLPRICE = (SELECT MAX(SELLPRICE) FROM PRODUCT_MASTER);

12. select ename from EMP where comm IS null;

13. select SUM(sal)from EMP;
