-- P-14 Retrieve data from multiple tables using sub queries.

1) SELECT dname
FROM dept
WHERE loc = (SELECT loc FROM dept WHERE loc = 'New York');

2) SELECT LOC
FROM DEPT
WHERE DEPTNO = 
( SELECT DEPTNO FROM EMP  WHERE JOB = 'President');

3) SELECT ENAME
FROM EMP
WHERE JOB = 'Manager'
AND DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'Research');

4) SELECT JOB
FROM EMP
WHERE EMPNO = (SELECT EMPNO FROM EMP WHERE EMPNO = 7900);

5) SELECT MAX(EMP_COUNT) AS MAX_COUNT
FROM ( SELECT DEPTNO, COUNT(*) 
AS EMP_COUNT FROM EMP GROUP BY DEPTNO);

6) SELECT *
FROM CLIENT
WHERE Clientno IN (SELECT Clientno
    FROM SALES_ORDER1
    WHERE Orderstatus = 'cancelled');

7) 1 -  ALTER TABLE SALES_ORDER_DETAILS1
ADD ORDERDATE DATE;

UPDATE SALES_ORDER_DETAILS1
SET ORDERDATE = '2004-04-03'
WHERE ORDERNO = 'O19001';

UPDATE SALES_ORDER_DETAILS1
SET ORDERDATE = TO_DATE('2004-04-03', 'YYYY-MM-DD')
WHERE ORDERNO = 'O19001';

2 -  UPDATE SALES_ORDER_DETAILS1
SET ORDERDATE = '2004-04-03'
WHERE ORDERNO = 'O19001'; 


(main)
SELECT pm.PRODUCTNO, pm.DESCRIPTION
FROM PRODUCT_MASTER pm
JOIN SALES_ORDER_DETAILS1 sod
ON pm.PRODUCTNO = sod.PRODUCTNO
WHERE sod.ORDERDATE = TO_DATE('03-Apr-04', 'DD-MON-YY');

8)  (DONT WRITE THIS)UPDATE SALES_MASTER
SET CITY = 'Madras'
WHERE CITY = 'Mumbai';

 (MANI)SELECT * FROM SALES_MASTER
WHERE CITY = (SELECT 'Madras'
    FROM SALES_MASTER
    WHERE CITY = 'Madras');


9)  SELECT pm.Productname
FROM PRODUCT_MASTER pm
WHERE pm.Productno = (
    SELECT Productno
    FROM SALES_ORDER_DETAILS1
    WHERE Rate = (
        SELECT MAX(Rate)
        FROM SALES_ORDER_DETAILS1));


10)  SELECT Clientno
FROM (
    SELECT Clientno
    FROM SALES_ORDER1
    GROUP BY Clientno
    ORDER BY COUNT(Orderno) DESC
)
WHERE ROWNUM = 1;
